server:
  port: 8081

telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME:MyTodoListBot}
    token: ${TELEGRAM_BOT_TOKEN:${TELEGRAM_KEY:}}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_URL}

backend:
  url: ${BACKEND_URL:http://localhost:8080}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}