server:
  port: 8081

telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_URL}

backend:
  url: ${BACKEND_URL:http://localhost:8080}
