package com.springboot.MyTodoList.features.user;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.*;

/*
    representation of the USER table that exists already
    in the autonomous database

    CREATE TABLE TODOUSER.USERS (
        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- ID autoincremental
        NAME VARCHAR2(50),        -- Campo para nombres, longitud máxima de 50 caracteres
        LASTNAME VARCHAR2(50),    -- Campo para apellidos, longitud máxima de 50 caracteres
        PHONENUMBER NUMBER(10),        -- Campo numérico, con un máximo de 10 dígitos
        USERPASSWORD VARCHAR2(100),    -- Campo para contraseñas, longitud máxima de 100 caracteres
        PRIMARY KEY (ID) -- Define ID como clave primaria
   );
 */
@Entity
@Table(name = "Users")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int userId;

    @Column(name = "name")
    String name;

    @Column(name = "email")
    String email;

    public User(){}

    public User(int userId, String name, String email){
        this.userId = userId;
        this.name = name;
        this.email = email;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
        name = "user_roles", // The join table
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private java.util.Set<com.springboot.MyTodoList.features.role.Role> roles;

    public int getUserId(){
        return userId;
    }

    public void setUserId(int userId){
        this.userId=userId;
    }

    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name=name;
    }

    
    public String getEmail(){
        return email;
    }

    public void setEmail(String email){
        this.email=email;
    }

}