#Local application properties (LOCALDEV profile MUST be active to use this)
app:
  base-url: http://localhost:8080

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@taskmanagerdb_tp?TNS_ADMIN=${TNS_ADMIN:./wallet}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          oci:
            redirect-uri: "${app.base-url}/login/oauth2/code/oci"