# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kubernetes DB Connection (injected via environment variables)
spring.datasource.url=jdbc:oracle:thin:@${TODO_PDB_NAME}_tp?TNS_ADMIN=/mtdrworkshop/creds
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# UCP Connection Pool
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

# Logging
logging.level.root=info
logging.file.name=logs.log
logging.level.oracle.ucp=warn
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE

# Third-Party APIs (injected via environment variables)
gemini.api.url=${GEMINI_URL}
gemini.api.key=${GEMINI_API_KEY}

# Telegram (injected via environment variables)
telegram.bot.token=${TELEGRAM_KEY}
telegram.bot.name=${TELEGRAM_BOT_NAME}
jwt.secret.key=${JWT_SECRET_KEY}
oci.domain.url=${OCI_PROVIDER_URL}
oci.domain.url=${OCI_PROVIDER_URL}
oci.client.id=${OCI_CLIENT_ID}
oci.client.secret=${OCI_CLIENT_SECRET}
oci.group.id=${OCI_GROUP_ID}
oci.tenancy.email=${TENANCY_EMAIL}
oci.tenancy.ocid=${TENANCY_OCID}
oci.tenancy.name=${TENANCY_NAME}
spring.security.oauth2.client.registration.oci.client-id=${OCI_CLIENT_ID}
spring.security.oauth2.client.registration.oci.client-secret=${OCI_CLIENT_SECRET}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}