#Application properties (BASE)
spring:
  jpa:
    database-platform: org.hibernate.community.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    # This is not used when deployed in Kubernetes. Just for local testing
    # url: jdbc:oracle:thin:@adbps_medium?TNS_ADMIN=/Users/psong/Downloads/Wallet_ADBPS
    # username: admin
    # password: WELcome__12345
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: "select * from dual"
      connection-pool-name: connectionPoolName1
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30

  #      Security Config
  security:
    oauth2:
      client:
        registration:
          oci:
            client-id: ${OCI_CLIENT_ID}
            client-secret: ${OCI_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/oci"
        provider:
          oci:
            authorization-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com:443/oauth2/v1/authorize
            token-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com:443/oauth2/v1/token
            jwk-set-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com:443/admin/v1/SigningCert/jwk
            user-info-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com:443/oauth2/v1/userinfo
            user-name-attribute: sub



logging:
  level:
    root: INFO
    oracle:
      ucp: WARN
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          TRACE: INFO
  file:
    name: logs.log

deepseek:
  api:
    key: sk-test
    url: https://api.deepseek.com/v1/chat/completions

telegram:
  bot:
    token: ${TELEGRAM_KEY}
    name: ${TELEGRAM_BOT_NAME}
