app:
  base-url: ${APP_REDIRECT_BASE_URL:http://localhost:8080}
  frontend-url: ${APP_FRONTEND_URL:${app.base-url}}

logging:
  file:
    name: logs.log
  level:
    root: info
    oracle.ucp: warn
    org.hibernate:
      SQL: DEBUG
      type: TRACE
      # Nested descriptor to handle the long property name
      type.descriptor.sql.BasicBinder: TRACE

spring:
  # Hibernate Settings
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # DataSource Connection & UCP Settings
  datasource:
    url: jdbc:oracle:thin:@${TODO_PDB_NAME}_tp?TNS_ADMIN=/mtdrworkshop/creds
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select * from dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30

  security:
    oauth2:
      client:
        registration:
          oci:
            client-id: ${OCI_CLIENT_ID}
            client-secret: ${OCI_CLIENT_SECRET}
            scope: openid, profile, email, offline_access
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "${app.base-url}/login/oauth2/code/oci"
        provider:
          oci:
            authorization-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com/oauth2/v1/authorize
            token-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com/oauth2/v1/token
            jwk-set-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com/admin/v1/SigningCert/jwk
            user-info-uri: https://idcs-0afee46b18294db68c4a47945c38f043.identity.oraclecloud.com/oauth2/v1/userinfo
            user-name-attribute: sub

# Custom & Third-Party Integrations
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_URL}

telegram:
  bot:
    token: ${TELEGRAM_KEY}
    name: ${TELEGRAM_BOT_NAME}

oci:
  domain:
    url: ${OCI_PROVIDER_URL}
  client:
    id: ${OCI_CLIENT_ID}
    secret: ${OCI_CLIENT_SECRET}
  group:
    id: ${OCI_GROUP_ID}
  tenancy:
    email: ${TENANCY_EMAIL}
    ocid: ${TENANCY_OCID}
    name: ${TENANCY_NAME}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}