apiVersion: v1
kind: Service
metadata:
  name: todolistapp-springboot-service
  namespace: mtdrworkshop
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: todolistapp-springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp-springboot-deployment
  namespace: mtdrworkshop
spec:
  selector:
    matchLabels:
      app: todolistapp-springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: todolistapp-springboot
        version: v1
    spec:
      containers:
        - name: todolistapp-springboot
          image: ${DOCKER_REGISTRY}/todolistapp-springboot:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbuser
            - name: TODO_PDB_NAME
              value: "${TODO_PDB_NAME}"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@${TODO_PDB_NAME}_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "${OCI_REGION}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret-key
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: gemini-api-key
            - name: GEMINI_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: gemini-url
            - name: TELEGRAM_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: telegram-key
            - name: TELEGRAM_BOT_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: telegram-bot-name
            - name: OCI_PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: oci-provider-url
            - name: OCI_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: oci-client-id
            - name: OCI_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: oci-client-secret
            - name: OCI_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: oci-group-id
            - name: TENANCY_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: tenancy-email
            - name: TENANCY_OCID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: tenancy-ocid
            - name: TENANCY_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: tenancy-name
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: ocir-secret
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: todolistapp-springboot
